version: "3.9"

services:
  viz:
    build:
      context: ${VIZ_DIR:-.}
      dockerfile: Dockerfile
    image: wielgoszinfo/carlaviz:0.9.13-develop
    entrypoint: [ "/bin/bash", "-c", "sleep 15 && ./docker/run.sh" ]
    expose:
      - 8089
    ports:
      - "127.0.0.1:${CARLAVIZ_FRONTEND_MAPPED_PORT:-49164}:8080"
      - "127.0.0.1:${CARLAVIZ_BACKEND_MAPPED_PORT:-49165}:${CARLAVIZ_BACKEND_PORT:-8081}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      CARLA_SERVER_HOST: server
      CARLA_SERVER_PORT: ${CARLA_SERVER_PORT:-2000}
      CARLAVIZ_BACKEND_HOST: ${CARLAVIZ_BACKEND_HOST:-localhost}
      CARLAVIZ_BACKEND_PORT: ${CARLAVIZ_BACKEND_PORT:-8081}
    depends_on:
      - server
